global:
  scrape_interval: 1s
  scrape_timeout: 1s

scrape_configs:
  - job_name: "pastryshop_metrics"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["pastryshop:8080"]
